@startuml "class" 

skinparam linetype polyline
package model {
  class User {
    + String UID
    + String name
    + String password
    + String adress
    + String email
    + int florains
    + boolean sleepMode
  }

  User o-- Ad

  Enum AdType {
    SERVICE
    GOOD
  }

  class Ad {
    + String name
    + boolean isOffer
    + String description
    + String imagePath
    + int cost
    + String adress
    + double maxDistance
    + Date start
    + Date end
    + Duration duration
  }
  Ad o--> AdType
}

@enduml